# Назарьин Артем 
#### НПМбд-01-19


<h1><center>LU / LUP разложения</center></h1>


<font size="4"> <strong> LU-разложение </strong> — это представление матрицы A в виде A=LU, где L — нижнетреугольная матрица с еденичной диагональю, а U — верхнетреугольная матрица. LU-разложение является модификациеё метода Гаусса. Основные применения данного алгоритма — решение систем алгебраических уравнений, вычисление определителя, вычисление обратной матрицы и др. 
<font size="4"> <h3> Реализация LU-разложения </h3>


LU-разложение может быть реализовано на Python при помощи библиотеки numpy как с двойным циклом for, так и без него. Для работы с алгоритмами необходимо импортировать библиотеки numpy и scipy (вторую библиотеку мы будем использовать для проверки работы алгоритмов. </font>

In [2]:
import numpy as np
import scipy.linalg

<font size="4"> В качестве матрицы A возьмем: 
<img src="https://latex.codecogs.com/gif.latex?A=\begin{pmatrix}%2010&-7&0%20\\%20-3&6%20&2%20\\%205&-1%20&5%20\end{pmatrix}">
Пример реализации алгоритма с двойным циклом for: </font>

In [3]:
matrix = np.array([[10, -7, 0], 
                   [-3, 6, 2], 
                   [5, -1, 5.]])

def LU(A):
    n = A.shape[0]
    U = np.copy(A)
    L = np.eye(n)
    for i in range(n):
        k = U[i,i]
        for j in range(i+1, n):
            L[j,i] = U[j,i] / k
            U[j] = U[j] - L[j,i] * U[i]
    return L,U
LU(matrix)

(array([[ 1.        ,  0.        ,  0.        ],
        [-0.3       ,  1.        ,  0.        ],
        [ 0.5       ,  0.64102564,  1.        ]]),
 array([[10.        , -7.        ,  0.        ],
        [ 0.        ,  3.9       ,  2.        ],
        [ 0.        ,  0.        ,  3.71794872]]))

<font size="4"><center> По условию двойной цикл for нас не удовлетворяет: попробуем немного изменить программу: </center></font>



In [4]:
def lu_decomposition(A):
    n = A.shape[0]
    U = np.copy(A)
    L = np.eye(n)
    for i in range(n - 1):
        L[i + 1:, i] = U[:, i][i + 1:] / U[i, i]
        m = np.reshape(L[i + 1:, i],(n - i - 1, 1))   #переформировываем значения L[i + 1:, i] из строки в столбец
        U[i + 1:, ] -= m * U[i]
    return L, U
lu_decomposition(matrix)

(array([[ 1.        ,  0.        ,  0.        ],
        [-0.3       ,  1.        ,  0.        ],
        [ 0.5       ,  0.64102564,  1.        ]]),
 array([[10.        , -7.        ,  0.        ],
        [ 0.        ,  3.9       ,  2.        ],
        [ 0.        ,  0.        ,  3.71794872]]))

<font size="4"> При помощи <strong> numpy.copy </strong> делаем копию  U для матрицы A, при помощи <strong> numpy.eye </strong> делаем единичную матрицу L. Цель: заполнить "нижний треугольник" матрицы L и "верхний треугольник" матрицы U. 
Берем цикл for с i от 1 до числа строк/столбцов нашей матрицы (данное число мы получим при помощи <strong> shape </strong>). Для того, чтобы заполнить значения под единицами в матрице L, <strong> делим элементы i-столбца под i-строкой на элемент U[i,i] </strong>. Для того, чтобы обнулить значения под i-м элементом i-й строки, <strong> вычитаем из области под i-й строкой i-ю строку, умноженную на коэффициент m </strong>.  
Затем проверяем правильность работы алгоритма при помощи <strong>scipy.linalg.lu</strong>: </font>

In [5]:
P,L,U = scipy.linalg.lu(matrix)
print(L)
print(U)

[[ 1.          0.          0.        ]
 [-0.3         1.          0.        ]
 [ 0.5         0.64102564  1.        ]]
[[10.         -7.          0.        ]
 [ 0.          3.9         2.        ]
 [ 0.          0.          3.71794872]]


<font size="4"> Перейдем к LUP-разложению:

<strong> LUP-разложение </strong> — это представление данной матрицы A в виде произведения PA = LU где матрица L является нижнетреугольной с единицами на главной диагонали, U — верхнетреугольная общего вида, а P — т. н. матрица перестановок, получаемая из единичной матрицы путём перестановки строк или столбцов. <em> Определение взято из википедии. </em>

<h3> Реализация LUP-разложения </h3>

LUP-разложение может быть реализовано на Python при помощи библиотеки numpy как с тройным циклом for, так и без него. Матрица A все та же. Пример реализации при помощи тройного цикла:
</font>


In [6]:
def lu_factor(A):
    n = A.shape[0]
    piv = np.arange(0,n)
    for k in range(n-1):
        max_row_index = np.argmax(abs(A[k:n,k])) + k
        piv[[k,max_row_index]] = piv[[max_row_index,k]]
        A[[k,max_row_index]] = A[[max_row_index,k]]

        # LU 
        for i in range(k+1,n):          
            A[i,k] = A[i,k]/A[k,k]      
            for j in range(k+1,n):      
                A[i,j] -= A[i,k]*A[k,j] 

    return [A,piv]
lu_factor(matrix)

[array([[10.        , -7.        ,  0.        ],
        [-0.3       ,  3.9       ,  2.        ],
        [ 0.5       ,  0.64102564,  3.71794872]]),
 array([0, 1, 2])]

<font size="4"> По условию тройной цикл for нас не удовлетворяет: попробуем немного изменить программу.
Можно ввести функцию <strong> change_rows </strong>, отвечающую за перестановку строк. </font>

In [20]:
def change_rows(A, i, j):
    if i == j:
        return A
    A[i], A[j] = A[j], np.copy(A[i])
        
    
def lup_factor(A):
    n = A.shape[0]
    U = np.copy(A)
    L = np.zeros((n, n))
    P = np.eye(n)
    for i in range(n-1):
        max_row_index = np.argmax(abs(A[i:n,i])) + i
        if max_row_index != i:
            change_rows(U, i, max_row_index)
            change_rows(L, i, max_row_index)
            change_rows(P, i, max_row_index)
            L[i + 1:, k] = U[:, i][i + 1:] / U[i, i]
            m = np.reshape(L[i + 1:, i],(n - i - 1, 1))
            U[i + 1:, ] -= m * U[i]
        return P, L + np.eye(n), U
lu_factor(matrix)
print(L)
print(U)

[[ 1.          0.          0.        ]
 [-0.3         1.          0.        ]
 [ 0.5         0.64102564  1.        ]]
[[10.         -7.          0.        ]
 [ 0.          3.9         2.        ]
 [ 0.          0.          3.71794872]]


<font size="4"> При помощи <strong> numpy.copy </strong> делаем копию  U для матрицы A, при помощи <strong> numpy.zeros </strong> делаем матрицу L, состоящую из нулей размера n x n (в данном случае 3 x 3), при помощи <strong> numpy.eye </strong> делаем единичную матрицу P. P — матрица перестановок. Суть:  при помощи <strong> numpy.argmax </strong> ищем максимальный (по модулю) элемент среди элементов i-го столбца, находящихся не выше i-й строки, затем меняем местами строку с этим элементом с i-й строкой. В остальном все так же, как в разложении LU. </font>

<font size="4"> <h3> Реализация алгоритма решения СЛАУ при помощи LU/LUP-разложений </h3>

Однажды найдя LU-разложение для матрицы мы можем очень быстро решать системы линейных алгебраических уравнений с различной правой частью.
<img src="https://latex.codecogs.com/gif.latex?A\cdot%20\bar{x}=\bar{b}">
<img src="https://latex.codecogs.com/gif.latex?L\cdot%20U\cdot%20\bar{x}=\bar{b}">
<img src="https://latex.codecogs.com/gif.latex?\bar{y}=U\cdot%20\bar{x}">
<img src="https://latex.codecogs.com/gif.latex?L\cdot%20\bar{y}=\bar{b}">
<center> Так как <strong>L</strong> — нижнетреугольная матрица, то очень легко находим $\tilde{y}$ </center>
Решаем <img src="https://latex.codecogs.com/gif.latex?U\cdot%20\bar{x}%20=%20\bar{y}">
    <center> Легко находим $\tilde{x}$, так как <strong> U </strong> — верхнетреугольная матрица </center>
</font>



<font size="4"> Для поиска $\tilde{y}$ используем прямую подстановку. Первый элемент будет равен первому элементу вектора b. Последующие ряды будут находиться вычитанием из b[i] скалярного произведения i-ой строки (реализованного при помощи <strong> numpy.dot </strong> c элементами от 0 до i-1 вектора y с элементами от 0 до i-1, деленного на L[i,i] (т.е. на единицы)
Для поиска $\tilde{x}$ используем обратную подстановку. 
Первый элемент будет равен последнему элементу вектора b, деленного на U[i, i]. Последующие ряды будут находиться вычитанием из b[i] скалярного произведения i-ой строки c элементами от 0 до i-1 вектора y с элементами от 0 до i-1, деленного на U[i,i].
</font>

In [23]:
matrix = np.array([[10, -7, 0], 
                   [-3, 6, 2], 
                   [5, -1, 5.]])
b = np.array([1, 0, 0])
L = np.array([[1., 0.,0.],
            [-0.3, 1., 0.],
            [0.5, 0.64102564,1.]])
U = np.array([[10., -7.,0.],
            [ 0., 3.9, 2.],
            [ 0.,0.,3.71794872]])

def fw_substitution(L, b):
    n = L.shape[0]
    y = np.zeros_like(b, dtype=np.double);
    y[0] = b[0] / L[0, 0]
    for i in range(1, n):
        y[i] = (b[i] - np.dot(L[i,:i], y[:i])) / L[i,i]
    return y

def back_substitution(U, y):
    n = U.shape[0]
    x = np.zeros_like(y, dtype=np.double);
    x[-1] = y[-1] / U[-1, -1]
    for i in range(n-2, -1, -1):
        x[i] = (y[i] - np.dot(U[i,i:], x[i:])) / U[i,i]
        
    return x
def lu_solve(A, b):
    y = fw_substitution(L, b)
    return back_substitution(U, y)

lu_solve(matrix, b)

array([ 0.22068966,  0.17241379, -0.1862069 ])

<font size="4"> Проверяем правильность работы алгоритма при помощи <strong>linalg.solve</strong>: </font>

In [22]:
np.linalg.solve(matrix, b)

array([ 0.22068966,  0.17241379, -0.1862069 ])

Разница между методами состоит в том, что LU - чистая форма разложения, а для LUP используются перестановки строк, что позволяет решить проблему при наличии нулевого члена матрицы. 